before_script:
 - pkill -f milton.py
 - cd ~/milton
 - . ~/milton/venv/bin/activate
 - pip install -U -r requirements.txt

run:
 script:
  - cd ~/milton
  - . venv/bin/activate
  - nohup python milton.py &